

function generateNavbar(nav, selectedItem) {
    navbar = nav.append("div")
        .attr("class", "maingrid")
        .append("div")
        .style("padding", "15px 0px 0px 0px")
        .append("div")
        .attr("class", "navbar row")
        .style("align-items", "center")
    navbar.append("a")
        .attr("href", "/index.html")
        .style("text-decoration", "none")
        .style("min-width", 100)
        .append("img")
        .attr("draggable", false)
        .attr("ondragstart", "return false;")
        .attr("src", "/pictures/signature.png")
        .style("height", 120)
        .style("z-index", 50)
    links = navbar.append("div")
        .style("position", "absolute")
        .style("font-family", "Montserrat")
        .style("right", 30)
        .style("top", 50)
        .style("display", "flex")
        .style("align-items", "center")
    links.append("div")
        .attr("class", selectedItem == "about" ? "active" : "")
        .append("a")
        .attr("href", "/index.html")
        .text("ABOUT")
    links.append("div")
        .attr("class", selectedItem == "projects" ? "active" : "")
        .append("a")
        .attr("href", "/work.html")
        .text("WORK")
    links.append("div")
        .attr("class", selectedItem == "projects" ? "active" : "")
        .append("a")
        .attr("href", "/projects.html")
        .text("PROJECTS")
    links.append("div")
        .attr("class", selectedItem == "resume" ? "active" : "")
        .append("a")
        .attr("href", "/JessicaHongResume.pdf")
        .text("RESUME")
}

function generateFooter(foot) {
    footer = foot.append("div")
        .attr("class", "maingrid")
        .style("padding", "48px 0px 48px 0px")
        .append("div")
        .attr("class", "row")
    footer.append("div")
        .attr("class", "divider")
        .style("margin-bottom", 48)
    links = footer.append("div")
        .style("text-align", "center")
        .style("width", "100%")
        .style("display", "flex")
        .style("justify-content", "center")
        .style("align-items", "center")
    const targets = [
        { href: "https://www.linkedin.com/in/jessicahong9/", icon: "fab fa-linkedin-in" },
        { href: "mailto:jwh296@cornell.edu", icon: "fas fa-envelope" }
    ]
    targets.forEach(target => {
        links.append("a")
            .attr("href", target.href)
            .style("padding-left", 5)
            .style("text-decoration", "none")
            .attr("target", "_blank")
            .append("i")
            .attr("class", target.icon)
    });
}
